# Generated by Django 6.0.6 on 2026-07-08 16:30

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Nationality'),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this token.', primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the token.', max_length=64, unique=True, verbose_name='Token hash')),
                ('expires_at', models.DateTimeField(help_text='Date and time when this token expires.', verbose_name='Expires at')),
                ('used_at', models.DateTimeField(blank=True, help_text='Date and time when this token was used.', null=True, verbose_name='Used at')),
                ('created_ip', models.GenericIPAddressField(blank=True, help_text='IP address used when this token was created.', null=True, verbose_name='Created IP')),
                ('user_agent', models.TextField(blank=True, help_text='Browser or device used to request this token.', verbose_name='User agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(help_text='User associated with this verification token.', on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email verification token',
                'verbose_name_plural': 'Email verification tokens',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user'], name='evt_user_idx'), models.Index(fields=['expires_at'], name='evt_expiry_idx'), models.Index(fields=['used_at'], name='evt_used_idx'), models.Index(fields=['created_at'], name='evt_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this token.', primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the token.', max_length=64, unique=True, verbose_name='Token hash')),
                ('expires_at', models.DateTimeField(help_text='Date and time when this token expires.', verbose_name='Expires at')),
                ('used_at', models.DateTimeField(blank=True, help_text='Date and time when this token was used.', null=True, verbose_name='Used at')),
                ('created_ip', models.GenericIPAddressField(blank=True, help_text='IP address used when this token was created.', null=True, verbose_name='Created IP')),
                ('user_agent', models.TextField(blank=True, help_text='Browser or device used to request this token.', verbose_name='User agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(help_text='User associated with this password reset token.', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Password reset token',
                'verbose_name_plural': 'Password reset tokens',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user'], name='prt_user_idx'), models.Index(fields=['expires_at'], name='prt_expiry_idx'), models.Index(fields=['used_at'], name='prt_used_idx'), models.Index(fields=['created_at'], name='prt_created_idx')],
            },
        ),
    ]
