# Generated by Django 6.0.6 on 2026-07-23 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_nationality_emailverificationtoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChangeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this token.', primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the token.', max_length=64, unique=True, verbose_name='Token hash')),
                ('expires_at', models.DateTimeField(help_text='Date and time when this token expires.', verbose_name='Expires at')),
                ('used_at', models.DateTimeField(blank=True, help_text='Date and time when this token was used.', null=True, verbose_name='Used at')),
                ('created_ip', models.GenericIPAddressField(blank=True, help_text='IP address used when this token was created.', null=True, verbose_name='Created IP')),
                ('user_agent', models.TextField(blank=True, help_text='Browser or device used to request this token.', verbose_name='User agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('new_email', models.EmailField(help_text='Email address requested by the user.', max_length=254, verbose_name='New email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email change token',
                'verbose_name_plural': 'Email change tokens',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user'], name='ect_user_idx'), models.Index(fields=['new_email'], name='ect_email_idx'), models.Index(fields=['expires_at'], name='ect_expiry_idx'), models.Index(fields=['used_at'], name='ect_used_idx'), models.Index(fields=['created_at'], name='ect_created_idx')],
            },
        ),
    ]
